export interface ElementData {
  symbol: string;
  name: string;
  atomicNumber: number;
  state: "solid" | "liquid" | "gas";
  category: "metal" | "nonmetal" | "metalloid" | "noble_gas";
  color: string;
  magnetic: boolean;
  flammable: boolean;
  waterBehavior: "gas" | "sinks" | "floats" | "reacts_violently" | "floats_reacts" | "dissolves" | "reacts";
  conductive: boolean;
  acidReaction: "none" | "bubbles" | "strong_reaction" | "dissolves";
  brittleness: "gas" | "liquid" | "bends" | "shatters" | "crumbles";
  wikiPage: string;
  description: string;
  realLifeUses: string;
}

export const ELEMENTS: ElementData[] = [
  { symbol:"H",  name:"Hydrogen",   atomicNumber:1,  state:"gas",    category:"nonmetal",
    color:"#E8F4FD", magnetic:false, flammable:true,  waterBehavior:"gas",
    conductive:false, acidReaction:"none",            brittleness:"gas",
    wikiPage:"Hydrogen",
    description:"The lightest and most abundant element in the universe. Colorless, odorless, and highly flammable.",
    realLifeUses:"Rocket fuel, hydrogen fuel cells for clean energy, making ammonia for fertilizers. Makes up water (H₂O)." },
  { symbol:"He", name:"Helium",     atomicNumber:2,  state:"gas",    category:"noble_gas",
    color:"#F0F8FF", magnetic:false, flammable:false, waterBehavior:"gas",
    conductive:false, acidReaction:"none",            brittleness:"gas",
    wikiPage:"Helium",
    description:"A completely non-reactive noble gas. The second lightest element — colorless and odorless.",
    realLifeUses:"Party balloons and blimps, cooling MRI machines, deep-sea diving breathing tanks." },
  { symbol:"Li", name:"Lithium",    atomicNumber:3,  state:"solid",  category:"metal",
    color:"#C0C0C0", magnetic:false, flammable:true,  waterBehavior:"floats_reacts",
    conductive:true,  acidReaction:"bubbles",         brittleness:"bends",
    wikiPage:"Lithium",
    description:"The lightest metal. So soft it can be cut with a knife. Floats on water, then violently reacts with it.",
    realLifeUses:"Rechargeable batteries in phones and electric cars. Medications for bipolar disorder." },
  { symbol:"Be", name:"Beryllium",  atomicNumber:4,  state:"solid",  category:"metal",
    color:"#D3D3D3", magnetic:false, flammable:false, waterBehavior:"sinks",
    conductive:true,  acidReaction:"bubbles",         brittleness:"shatters",
    wikiPage:"Beryllium",
    description:"A light, stiff, brittle, and highly toxic metal. One of the lightest structural metals.",
    realLifeUses:"Aerospace components, X-ray equipment windows, nuclear reactor control rods." },
  { symbol:"B",  name:"Boron",      atomicNumber:5,  state:"solid",  category:"metalloid",
    color:"#8B4513", magnetic:false, flammable:false, waterBehavior:"sinks",
    conductive:false, acidReaction:"none",            brittleness:"shatters",
    wikiPage:"Boron",
    description:"A hard, brittle metalloid — not a metal, not a nonmetal. Found naturally in borax.",
    realLifeUses:"Borosilicate glass (Pyrex cookware), borax cleaning products, nuclear reactor control rods." },
  { symbol:"C",  name:"Carbon",     atomicNumber:6,  state:"solid",  category:"nonmetal",
    color:"#333333", magnetic:false, flammable:true,  waterBehavior:"sinks",
    conductive:true,  acidReaction:"none",            brittleness:"crumbles",
    wikiPage:"Carbon",
    description:"The basis of all life. Exists as graphite (soft, conductive, black) and diamond (hardest natural substance).",
    realLifeUses:"Pencils (graphite), diamonds, steel production. The backbone of every living molecule." },
  { symbol:"N",  name:"Nitrogen",   atomicNumber:7,  state:"gas",    category:"nonmetal",
    color:"#E8F4FD", magnetic:false, flammable:false, waterBehavior:"gas",
    conductive:false, acidReaction:"none",            brittleness:"gas",
    wikiPage:"Nitrogen",
    description:"Makes up 78% of Earth's atmosphere. Colorless, odorless, mostly unreactive.",
    realLifeUses:"Liquid nitrogen for freezing food and biological samples, fertilizers, food packaging." },
  { symbol:"O",  name:"Oxygen",     atomicNumber:8,  state:"gas",    category:"nonmetal",
    color:"#E8F8FF", magnetic:false, flammable:false, waterBehavior:"gas",
    conductive:false, acidReaction:"none",            brittleness:"gas",
    wikiPage:"Oxygen",
    description:"21% of our atmosphere. Essential for breathing. It supports combustion — doesn't burn itself, but makes things burn.",
    realLifeUses:"Medical oxygen tanks, steel and glass production, water treatment." },
  { symbol:"F",  name:"Fluorine",   atomicNumber:9,  state:"gas",    category:"nonmetal",
    color:"#FFFACD", magnetic:false, flammable:false, waterBehavior:"gas",
    conductive:false, acidReaction:"strong_reaction", brittleness:"gas",
    wikiPage:"Fluorine",
    description:"The most reactive element. A pale yellow gas that aggressively attacks almost every material it contacts.",
    realLifeUses:"Toothpaste and drinking water (prevents tooth decay), Teflon non-stick coating." },
  { symbol:"Ne", name:"Neon",       atomicNumber:10, state:"gas",    category:"noble_gas",
    color:"#FF6347", magnetic:false, flammable:false, waterBehavior:"gas",
    conductive:false, acidReaction:"none",            brittleness:"gas",
    wikiPage:"Neon",
    description:"A noble gas famous for its brilliant orange-red glow when electricity passes through it.",
    realLifeUses:"Neon signs, lasers, high-voltage indicators." },
  { symbol:"Na", name:"Sodium",     atomicNumber:11, state:"solid",  category:"metal",
    color:"#C0C0C0", magnetic:false, flammable:true,  waterBehavior:"reacts_violently",
    conductive:true,  acidReaction:"strong_reaction", brittleness:"bends",
    wikiPage:"Sodium",
    description:"A soft, silvery metal that reacts explosively with water, skittering across the surface and bursting into flame.",
    realLifeUses:"Table salt (NaCl), baking soda, soap-making, sodium-vapor yellow street lamps." },
  { symbol:"Mg", name:"Magnesium",  atomicNumber:12, state:"solid",  category:"metal",
    color:"#E8E8E8", magnetic:false, flammable:true,  waterBehavior:"sinks",
    conductive:true,  acidReaction:"bubbles",         brittleness:"bends",
    wikiPage:"Magnesium",
    description:"A light, silvery metal that burns with a blindingly bright white flame — so hot it even burns underwater.",
    realLifeUses:"Lightweight alloys for cars and aircraft, fireworks (white sparks), dietary supplements." },
  { symbol:"Al", name:"Aluminum",   atomicNumber:13, state:"solid",  category:"metal",
    color:"#C8C8C8", magnetic:false, flammable:false, waterBehavior:"sinks",
    conductive:true,  acidReaction:"bubbles",         brittleness:"bends",
    wikiPage:"Aluminium",
    description:"Lightweight, silvery metal that resists rust. The most abundant metal in Earth's crust.",
    realLifeUses:"Drink cans, aircraft bodies, kitchen foil, window frames, cooking pots." },
  { symbol:"Si", name:"Silicon",    atomicNumber:14, state:"solid",  category:"metalloid",
    color:"#708090", magnetic:false, flammable:false, waterBehavior:"sinks",
    conductive:false, acidReaction:"none",            brittleness:"shatters",
    wikiPage:"Silicon",
    description:"A shiny metalloid and semiconductor — its electrical conductivity can be precisely engineered.",
    realLifeUses:"Computer chips, solar panels, glass (sand = SiO₂), silicone rubber." },
  { symbol:"P",  name:"Phosphorus", atomicNumber:15, state:"solid",  category:"nonmetal",
    color:"#FFD700", magnetic:false, flammable:true,  waterBehavior:"sinks",
    conductive:false, acidReaction:"none",            brittleness:"crumbles",
    wikiPage:"Phosphorus",
    description:"Exists in forms: white phosphorus spontaneously ignites in air; red phosphorus (safer) is used in matches.",
    realLifeUses:"Fertilizers (plants need phosphorus), match heads (red phosphorus), DNA's phosphate backbone." },
  { symbol:"S",  name:"Sulfur",     atomicNumber:16, state:"solid",  category:"nonmetal",
    color:"#FFD700", magnetic:false, flammable:true,  waterBehavior:"sinks",
    conductive:false, acidReaction:"none",            brittleness:"shatters",
    wikiPage:"Sulfur",
    description:"Bright yellow, brittle solid. Burns with a blue flame. Hydrogen sulfide (H₂S) smells like rotten eggs.",
    realLifeUses:"Making sulfuric acid (most-produced industrial chemical), vulcanizing rubber, fungicides." },
  { symbol:"Cl", name:"Chlorine",   atomicNumber:17, state:"gas",    category:"nonmetal",
    color:"#90EE90", magnetic:false, flammable:false, waterBehavior:"gas",
    conductive:false, acidReaction:"none",            brittleness:"gas",
    wikiPage:"Chlorine",
    description:"A toxic yellow-green gas with a sharp, choking smell. Powerful disinfectant and bleaching agent.",
    realLifeUses:"Disinfecting swimming pools and drinking water, making PVC plastic, household bleach." },
  { symbol:"Ar", name:"Argon",      atomicNumber:18, state:"gas",    category:"noble_gas",
    color:"#E8F4FD", magnetic:false, flammable:false, waterBehavior:"gas",
    conductive:false, acidReaction:"none",            brittleness:"gas",
    wikiPage:"Argon",
    description:"Third most abundant gas in Earth's atmosphere. A noble gas — completely unreactive.",
    realLifeUses:"Welding (prevents oxidation), filling incandescent bulbs, preserving ancient documents." },
  { symbol:"K",  name:"Potassium",  atomicNumber:19, state:"solid",  category:"metal",
    color:"#C0C0C0", magnetic:false, flammable:true,  waterBehavior:"reacts_violently",
    conductive:true,  acidReaction:"strong_reaction", brittleness:"bends",
    wikiPage:"Potassium",
    description:"Even more reactive than sodium. Ignites in air and reacts explosively with water — producing a purple flame.",
    realLifeUses:"Fertilizers (vital for plant growth), found abundantly in bananas, potassium nitrate in fireworks." },
  { symbol:"Ca", name:"Calcium",    atomicNumber:20, state:"solid",  category:"metal",
    color:"#E8E8E8", magnetic:false, flammable:false, waterBehavior:"reacts",
    conductive:true,  acidReaction:"bubbles",         brittleness:"bends",
    wikiPage:"Calcium",
    description:"A soft, silvery metal that slowly reacts with water. Essential for bones, teeth, and muscle function.",
    realLifeUses:"Building materials (limestone, cement, marble), dairy foods strengthen bones, chalk (CaCO₃)." },
  { symbol:"Fe", name:"Iron",       atomicNumber:26, state:"solid",  category:"metal",
    color:"#8B7355", magnetic:true,  flammable:false, waterBehavior:"sinks",
    conductive:true,  acidReaction:"bubbles",         brittleness:"bends",
    wikiPage:"Iron",
    description:"A strong, magnetic metal that rusts when exposed to water and oxygen. The most widely used metal on Earth.",
    realLifeUses:"Steel for buildings, cars, bridges; cast-iron pans; iron supplements; Earth's magnetic core is mostly iron." },
  { symbol:"Cu", name:"Copper",     atomicNumber:29, state:"solid",  category:"metal",
    color:"#B87333", magnetic:false, flammable:false, waterBehavior:"sinks",
    conductive:true,  acidReaction:"dissolves",       brittleness:"bends",
    wikiPage:"Copper",
    description:"Reddish-orange, excellent electrical conductor. Gradually turns green (patina) when exposed to air.",
    realLifeUses:"Electrical wiring, plumbing pipes, coins. The Statue of Liberty is covered in copper." },
  { symbol:"Ag", name:"Silver",     atomicNumber:47, state:"solid",  category:"metal",
    color:"#C0C0C0", magnetic:false, flammable:false, waterBehavior:"sinks",
    conductive:true,  acidReaction:"none",            brittleness:"bends",
    wikiPage:"Silver",
    description:"The best conductor of electricity and heat of all metals. Has natural antimicrobial properties.",
    realLifeUses:"Jewelry, silverware, electrical contacts, old photographic film, antibacterial coatings." },
  { symbol:"Au", name:"Gold",       atomicNumber:79, state:"solid",  category:"metal",
    color:"#FFD700", magnetic:false, flammable:false, waterBehavior:"sinks",
    conductive:true,  acidReaction:"none",            brittleness:"bends",
    wikiPage:"Gold",
    description:"Dense, soft, shiny — never tarnishes or corrodes. One of the rarest and most valuable elements.",
    realLifeUses:"Jewelry, circuit board connectors in electronics, currency reserves, dental fillings." },
  { symbol:"Hg", name:"Mercury",    atomicNumber:80, state:"liquid", category:"metal",
    color:"#B0B0B0", magnetic:false, flammable:false, waterBehavior:"sinks",
    conductive:true,  acidReaction:"dissolves",       brittleness:"liquid",
    wikiPage:"Mercury_(element)",
    description:"The only metal liquid at room temperature. Extremely dense and highly toxic. Forms mirror-like silvery droplets.",
    realLifeUses:"Old thermometers and barometers, fluorescent light bulbs, dental amalgam (being phased out due to toxicity)." },
  { symbol:"I",  name:"Iodine",     atomicNumber:53, state:"solid",  category:"nonmetal",
    color:"#4B0082", magnetic:false, flammable:false, waterBehavior:"sinks",
    conductive:false, acidReaction:"none",            brittleness:"shatters",
    wikiPage:"Iodine",
    description:"A dark purple-black solid that sublimes (turns directly to purple gas) when heated. Essential for thyroid function.",
    realLifeUses:"Antiseptic for wounds, iodized table salt (prevents thyroid deficiency), thyroid medication." },
  { symbol:"Br", name:"Bromine",    atomicNumber:35, state:"liquid", category:"nonmetal",
    color:"#8B0000", magnetic:false, flammable:false, waterBehavior:"sinks",
    conductive:false, acidReaction:"none",            brittleness:"liquid",
    wikiPage:"Bromine",
    description:"One of only two elements liquid at room temperature (along with mercury). A dark red, toxic, fuming liquid.",
    realLifeUses:"Flame retardants in electronics and furniture, pool/spa water treatment, some pharmaceuticals." },
  { symbol:"Xe", name:"Xenon",      atomicNumber:54, state:"gas",    category:"noble_gas",
    color:"#E8F4FD", magnetic:false, flammable:false, waterBehavior:"gas",
    conductive:false, acidReaction:"none",            brittleness:"gas",
    wikiPage:"Xenon",
    description:"A heavy noble gas that glows intense blue-white when electricity passes through it.",
    realLifeUses:"High-intensity car headlights (HID/xenon lamps), medical anesthesia, ion thrusters on spacecraft." },
  { symbol:"Zn", name:"Zinc",       atomicNumber:30, state:"solid",  category:"metal",
    color:"#A8A9AD", magnetic:false, flammable:false, waterBehavior:"sinks",
    conductive:true,  acidReaction:"bubbles",         brittleness:"bends",
    wikiPage:"Zinc",
    description:"A bluish-white metal that coats steel to prevent rust — this process is called galvanization.",
    realLifeUses:"Galvanizing steel (prevents rust on cars and lampposts), zinc-carbon batteries, sunscreen (zinc oxide)." },
  { symbol:"Pb", name:"Lead",       atomicNumber:82, state:"solid",  category:"metal",
    color:"#888888", magnetic:false, flammable:false, waterBehavior:"sinks",
    conductive:true,  acidReaction:"none",            brittleness:"bends",
    wikiPage:"Lead",
    description:"Very dense, soft, dull grey metal. Highly toxic — its use in paint and plumbing is now banned in most countries.",
    realLifeUses:"Car batteries (lead-acid type), radiation shielding in X-ray rooms, old water pipes (being replaced globally)." }
];
